#' Create folder with ODMAP structure
#'
#' This function creates an empty folder following the ODMAP structure
#' (Overview, Data, Modeling, Assessment, and Prediction). It is intended to
#' be used for habitat, movement, and connectivity modeling and suggested to
#' be used by species (i.e. one folder per species), but this can be used
#' in other ways depending of the user preferences.
#'
#' The function will probably throw some warnings because R project files are
#' created in nested folders where a R proj file is already existing. The user
#' needs to mannually accept that to allow the creation of these files, which
#' makes it easier for one to set relative paths for each of the modeling
#' steps.
#'
#' @param path `[character]` \cr Path where the folder will be created, including
#' intended folder name. If no argument is provided, the structure is created in
#' the current working directory,
#' @param overwrite `[logical(1)=FALSE]` \cr Should the folder be overwritten if'
#' it already exists? Default is `FALSE`.
#'
#' @examples
#' create_odmap(path = "./test")
#'
#' @export
create_odmap <- function(path = ".",
                         overwrite = FALSE) {

  # check path and create it if
  path <- usethis:::user_path_prep(path)
  if(path != ".") {
    if(!dir.exists(path)) {
      usethis:::create_directory(path)
    } else {
      if(!overwrite) stop(paste0("The folder ",path," already exists."))
    }
  }

  #--- overview
  # create overview
  new_folder <- "01_overview/"
  usethis:::create_directory(paste0(path, "/", new_folder))

  # create readme on overview
  cat("# General overview

Here we should present a general overview of the project structure, aims, and outputs.

This is located within the folder 01_overview within the ODMAP structure.
In this folder we might also include files or sub-folders with project meeting notes, project decisions etc.",
      file = paste0(path, "/", new_folder, "/README.md"))

  #--- data
  # create data
  new_folder <- "02_data/"
  usethis:::create_project(paste0(path, "/", new_folder), rstudio = TRUE,
                           open = FALSE)

  # create readme on data
  cat("# Data

Here we add the data used in the project, separated as 'biological' and
'environmental' in two different folders. In each, we have a subfolder for
raw data (in the raw/ folder) and the processed data
(in the processed/ folder). This folder has the structure of a R project,
with R functions in the R/ folder, functions of other programming languages
in the src/ folder, and the main scripts in the root directory.

Feel free to overwrite this text and brifly describe here your data, data
sources etc.",
      file = paste0(path, "/", new_folder, "/README.md"))

  # biological and evnironmental data
  for(data_type in c("bio", "env")) {
    # main folder
    usethis:::create_directory(paste0(path, "/", new_folder, "/", data_type))

    # create raw and processed folders
    usethis:::create_directory(paste0(path, "/", new_folder, "/", data_type, "/raw"))
    usethis:::create_directory(paste0(path, "/", new_folder, "/", data_type, "/processed"))
  }

  # We could create the R/ folder here but it is already created by the create_project
  # create src for non-R functions
  usethis:::create_directory(paste0(path, "/", new_folder, "/src"))

  #--- modeling
  # create modeling
  new_folder <- "03_modeling/"
  usethis:::create_directory(paste0(path, "/", new_folder))

  # biological and evnironmental data
  for(model_type in c("habitat", "movement", "connectivity", "assessment")) {

    if(!dir.exists(paste0(path, "/", new_folder, "/", model_type))) {
      # main folder
      usethis:::create_project(paste0(path, "/", new_folder, "/", model_type), rstudio = TRUE,
                               open = FALSE)

      # create readme on modeling
      cat(paste0("# ", model_type, " modeling

This folder has a structure of a R project with multiple sub-folder. They are:

- The `data` folder contains all input data (and metadata) used in the analysis.
It is intended for data that is already ready to be analyzed.
- The `doc` folder contains the manuscript, report, or text to be written.
- The `figs` directory contains figures generated by the analysis.
- The `maps` directory contains maps (e.g. tif,shp) generated by the analysis.
- The `output` folder contains any type of intermediate or output files (e.g.
simulation outputs, models, processed data sets, etc.).
- The `R` directory contains R scripts with function definitions, and it is supplemented
by the `src` folder with function definitions in other programming languages (e.g. Julia, Python).
- The `archive` folder contains old scripts and code.
- The `reports` folder contains RMarkdown files that document the analysis or report on results.

Feel free to overwrite this text and briefly describe here your modeling process or
framework here."),
          file = paste0(path, "/", new_folder, "/", model_type, "/README.md"))

      # create project folders for modeling type
      usethis:::create_directory(paste0(path, "/", new_folder, "/", model_type, "/archive"))
      usethis:::create_directory(paste0(path, "/", new_folder, "/", model_type, "/data"))
      usethis:::create_directory(paste0(path, "/", new_folder, "/", model_type, "/doc"))
      usethis:::create_directory(paste0(path, "/", new_folder, "/", model_type, "/figs"))
      usethis:::create_directory(paste0(path, "/", new_folder, "/", model_type, "/maps"))
      usethis:::create_directory(paste0(path, "/", new_folder, "/", model_type, "/output"))
      # folder R/ already created
      usethis:::create_directory(paste0(path, "/", new_folder, "/", model_type, "/reports"))

    } else {
      warning("The folder for ", model_type, " modeling already exists.")
    }

  }

  #--- assessment
  # create assessment
  new_folder <- "04_assessment/"
  usethis:::create_directory(paste0(path, "/", new_folder))

  # create readme on data
  cat("# Assessment

Here we document or perform analysis related to the assessment of the models.
This can include expert assessment, model assessment using alternative data etc.",
      file = paste0(path, "/", new_folder, "/README.md"))

  #--- assessment
  # create assessment
  new_folder <- "05_pediction/"
  usethis:::create_directory(paste0(path, "/", new_folder))

  # create readme on data
  cat("# Prediction

Here we can create sub-folders to store general model predictions or
use them for impact assessment, scenario analyses, presenting the results
as dashboards etc.",
      file = paste0(path, "/", new_folder, "/README.md"))

  cat("Done! The ODMAP structure was successfully created.")
}
